name: GitHub Actions Gates
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project name"
        required: true
        default: "project-a"

jobs:
  # This will create a GitHub environment through the GitHub API
  create-environment:
    name: Create GitHub Environment
    #environment:
    #  name: project-b
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Environment
        id: create-env
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/environments
          environment_name: ${{ github.event.inputs.project_name }}
          environment_url: ${{ github.event.inputs.project_name }}
          environment_description: "Environment for ${{ github.event.inputs.project_name }}"
          environment_protection_rules: |
            {
              "wait_timer": {
                "enabled": true,
                "wait_timer": 60
              }
            }
          environment_review_protection_rules: |
            {
              "wait_timer": {
                "enabled": true,
                "wait_timer": 60
              }
            }
          environment_deployment_branch_policy: |
            {
              "protected_branches": {
                "enabled": true,
                "protected_branches": [
                  "main"
                ]
              }
            }