name: GitHub Actions Environment
on:
  workflow_dispatch:

jobs:
  build:
    environment:
      name: project-a
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variable
        run: echo "Project name is $PROJECT_NAME"

      - name: Dump secret
        run: echo "${{ env.PROJECT_NAME }}" | sed 's/./& /g'
