name: GitHub Actions Environment
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project name"
        required: true
        default: "project-a"

jobs:
  build-project-a:
    name: Build Project A
    environment:
      name: project-a
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variable
        run: echo "Project name is $PROJECT_NAME"

      - name: Dump secret
        run: echo ${{ secrets.PROJECT_NAME }} | sed 's/./& /g'

      - name: Dump environment variable
        run: echo ${{ env.PROJECT_ENV }}

  build-b:
    name: Build Project B
    environment:
      name: project-b
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variable
        run: echo "Project name is $PROJECT_NAME"

      - name: Dump secret
        run: echo ${{ secrets.PROJECT_NAME }} | sed 's/./& /g'

      - name: Dump environment variable
        run: echo ${{ env.PROJECT_ENV }}

  build-input:
    name: Build Project Input
    environment:
      name: ${{ github.event.inputs.project_name }}
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variable
        run: echo "Project name is $PROJECT_NAME"

      - name: Dump secret
        run: echo ${{ secrets.PROJECT_NAME }} | sed 's/./& /g'

      - name: Dump environment variable
        run: echo ${{ env.PROJECT_ENV }}
